name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Release on Crates.io
      if: github.ref == 'refs/heads/master'
      run: |
        cargo login ${{ secrets.CARGO_TOKEN }}
        cargo publish
